
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dev.webfx.stack.orm.expression.parser.javacup;

/** CUP generated interface containing symbol constants. */
public interface ExpressionSymbols {
  /* terminals */
  public static final int GTEQ = 53;
  public static final int QUESTION_DOT = 50;
  public static final int NULLS = 12;
  public static final int MULT = 43;
  public static final int ANY = 26;
  public static final int LTEQ = 52;
  public static final int OBJ_STATE = 29;
  public static final int DESC = 10;
  public static final int LPAREN = 31;
  public static final int IMAGE = 30;
  public static final int UPDATE = 18;
  public static final int MINUS = 42;
  public static final int DELETE = 19;
  public static final int WHERE = 6;
  public static final int RPAREN = 32;
  public static final int AND = 55;
  public static final int NOT = 48;
  public static final int IS = 22;
  public static final int LT = 47;
  public static final int FIRST = 13;
  public static final int OFFSET = 16;
  public static final int OR = 56;
  public static final int IN = 24;
  public static final int COMMA = 37;
  public static final int DIV = 44;
  public static final int SELECT = 3;
  public static final int PLUS = 41;
  public static final int THIS = 28;
  public static final int DOT = 38;
  public static final int BOOLEAN = 60;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DISTINCT = 4;
  public static final int LIKE = 23;
  public static final int LIMIT = 15;
  public static final int LCURLY = 39;
  public static final int NULL = 58;
  public static final int EQEQ = 51;
  public static final int EXISTS = 21;
  public static final int NUMBER = 59;
  public static final int EQ = 45;
  public static final int GROUP_BY = 7;
  public static final int RCURLY = 40;
  public static final int LBRACK = 33;
  public static final int FROM = 5;
  public static final int ASC = 11;
  public static final int COLON = 35;
  public static final int LAST = 14;
  public static final int RBRACK = 34;
  public static final int DOUBLE_COLON = 36;
  public static final int ORDER_BY = 9;
  public static final int DOLLAR = 57;
  public static final int INSERT = 17;
  public static final int STRING = 61;
  public static final int QUESTION = 49;
  public static final int ALL = 27;
  public static final int EXPR_START = 2;
  public static final int AS = 25;
  public static final int GT = 46;
  public static final int NOTEQ = 54;
  public static final int SET = 20;
  public static final int IDENTIFIER = 62;
  public static final int HAVING = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXPR_START",
  "SELECT",
  "DISTINCT",
  "FROM",
  "WHERE",
  "GROUP_BY",
  "HAVING",
  "ORDER_BY",
  "DESC",
  "ASC",
  "NULLS",
  "FIRST",
  "LAST",
  "LIMIT",
  "OFFSET",
  "INSERT",
  "UPDATE",
  "DELETE",
  "SET",
  "EXISTS",
  "IS",
  "LIKE",
  "IN",
  "AS",
  "ANY",
  "ALL",
  "THIS",
  "OBJ_STATE",
  "IMAGE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "COLON",
  "DOUBLE_COLON",
  "COMMA",
  "DOT",
  "LCURLY",
  "RCURLY",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "QUESTION",
  "QUESTION_DOT",
  "EQEQ",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "AND",
  "OR",
  "DOLLAR",
  "NULL",
  "NUMBER",
  "BOOLEAN",
  "STRING",
  "IDENTIFIER"
  };
}

