// Generated by WebFx

module webfx.framework.client.i18n {

    // Direct dependencies modules
    requires java.base;
    requires javafx.base;
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.framework.shared.operation;
    requires webfx.platform.client.uischeduler;
    requires webfx.platform.shared.util;

    // Exported packages
    exports dev.webfx.framework.client.operations.i18n;
    exports dev.webfx.framework.client.services.i18n;
    exports dev.webfx.framework.client.services.i18n.spi;
    exports dev.webfx.framework.client.services.i18n.spi.impl;

    // Used services
    uses dev.webfx.framework.client.operations.i18n.ChangeLanguageRequestEmitter;
    uses dev.webfx.framework.client.services.i18n.spi.I18nProvider;

}