// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/dev/webfx/stack/orm/expression/parser/jflex/ExpressionLexer.flex


/* --------------------------Usercode Section------------------------ */

package dev.webfx.stack.orm.expression.parser.jflex;

import java_cup.runtime.*;
import        dev.webfx.stack.orm.expression.parser.javacup.ExpressionSymbols;
import static dev.webfx.stack.orm.expression.parser.javacup.ExpressionSymbols.*;


@SuppressWarnings("fallthrough")
public class ExpressionLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_SINGLE_QUOTE = 2;
  public static final int STRING_DOUBLE_QUOTE = 4;
  public static final int STRING_GRAVE_ACCENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\0\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\3\24\4\25\2\26\1\27\1\0\1\30\1\31\1\32"+
    "\1\33\1\0\1\34\1\35\1\34\1\36\1\37\1\34"+
    "\1\40\7\34\1\41\1\42\1\34\1\43\1\44\1\34"+
    "\1\45\3\34\1\46\1\34\1\47\1\50\1\51\1\0"+
    "\1\34\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\34\1\73\1\74\1\75\1\76\1\77"+
    "\1\100\1\101\1\102\1\34\1\103\1\104\1\105\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\17\1\20\1\21\1\22\1\23\1\24\3\25\1\26"+
    "\1\27\1\30\15\25\1\31\1\1\1\32\1\33\2\34"+
    "\1\35\1\1\2\33\1\36\1\37\1\0\1\2\1\40"+
    "\1\41\1\42\4\25\1\43\10\25\1\44\1\45\5\25"+
    "\1\46\5\25\1\46\1\47\1\50\1\51\2\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\2\0\2\25\1\61"+
    "\1\37\1\62\1\63\16\25\1\3\3\25\1\64\4\25"+
    "\1\52\1\0\3\25\1\65\5\25\1\66\3\25\1\67"+
    "\1\70\1\25\1\71\2\25\1\72\1\73\7\25\1\0"+
    "\1\74\1\75\1\25\1\76\1\25\1\77\1\100\3\25"+
    "\1\101\2\0\1\102\1\25\1\103\1\104\1\105\1\106"+
    "\1\25\1\107\1\110\2\0\2\25\1\111\1\112\1\113"+
    "\1\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\u0118\0\u015e\0\u01a4"+
    "\0\u0118\0\u0118\0\u01ea\0\u0118\0\u0118\0\u0118\0\u0118\0\u0118"+
    "\0\u0118\0\u0118\0\u0118\0\u0230\0\u0118\0\u0276\0\u0118\0\u02bc"+
    "\0\u0302\0\u0348\0\u0118\0\u038e\0\u03d4\0\u041a\0\u0118\0\u0118"+
    "\0\u0118\0\u0460\0\u04a6\0\u04ec\0\u0532\0\u0578\0\u05be\0\u0604"+
    "\0\u064a\0\u0690\0\u06d6\0\u071c\0\u0762\0\u07a8\0\u0118\0\u07ee"+
    "\0\u0118\0\u0834\0\u0118\0\u087a\0\u0118\0\u08c0\0\u0906\0\u094c"+
    "\0\u0118\0\u0118\0\u0992\0\u09d8\0\u0118\0\u0118\0\u0118\0\u0a1e"+
    "\0\u0a64\0\u0aaa\0\u0af0\0\u0b36\0\u0b7c\0\u0bc2\0\u0c08\0\u0c4e"+
    "\0\u0c94\0\u0cda\0\u0d20\0\u0d66\0\u0dac\0\u038e\0\u0df2\0\u0e38"+
    "\0\u0e7e\0\u0ec4\0\u0f0a\0\u0a64\0\u0f50\0\u0f96\0\u0fdc\0\u1022"+
    "\0\u1068\0\u0118\0\u0118\0\u0118\0\u0118\0\u10ae\0\u10f4\0\u0118"+
    "\0\u0118\0\u0118\0\u0118\0\u0118\0\u0118\0\u113a\0\u1180\0\u11c6"+
    "\0\u120c\0\u038e\0\u038e\0\u038e\0\u038e\0\u1252\0\u1298\0\u12de"+
    "\0\u1324\0\u136a\0\u13b0\0\u13f6\0\u143c\0\u1482\0\u14c8\0\u150e"+
    "\0\u1554\0\u159a\0\u15e0\0\u038e\0\u1626\0\u166c\0\u16b2\0\u038e"+
    "\0\u16f8\0\u173e\0\u1784\0\u17ca\0\u0118\0\u1810\0\u1856\0\u189c"+
    "\0\u18e2\0\u038e\0\u1928\0\u196e\0\u19b4\0\u19fa\0\u1a40\0\u038e"+
    "\0\u1a86\0\u1acc\0\u1b12\0\u038e\0\u038e\0\u1b58\0\u1b9e\0\u1be4"+
    "\0\u1c2a\0\u038e\0\u038e\0\u1c70\0\u1cb6\0\u1cfc\0\u1d42\0\u1d88"+
    "\0\u1dce\0\u1e14\0\u1e5a\0\u038e\0\u038e\0\u1ea0\0\u038e\0\u1ee6"+
    "\0\u038e\0\u038e\0\u1f2c\0\u1f72\0\u1fb8\0\u038e\0\u1ffe\0\u2044"+
    "\0\u038e\0\u208a\0\u038e\0\u0118\0\u038e\0\u038e\0\u20d0\0\u038e"+
    "\0\u038e\0\u2116\0\u215c\0\u21a2\0\u21e8\0\u0118\0\u0118\0\u038e"+
    "\0\u038e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\3\26\1\27\1\30\1\31\1\32"+
    "\1\33\4\34\1\35\1\36\5\34\1\37\1\5\1\40"+
    "\1\41\1\42\2\34\1\43\1\44\1\45\1\35\1\46"+
    "\1\47\2\34\1\50\1\34\1\51\1\52\2\34\1\53"+
    "\1\54\1\55\1\34\1\56\2\34\1\57\1\60\1\61"+
    "\2\62\1\63\2\62\1\64\4\62\1\65\35\62\1\66"+
    "\35\62\2\67\1\63\2\67\1\64\1\67\1\65\40\67"+
    "\1\66\35\67\2\70\1\63\2\70\1\64\42\70\1\66"+
    "\1\70\1\65\33\70\110\0\1\6\134\0\1\71\65\0"+
    "\1\72\111\0\1\73\4\0\1\74\106\0\4\26\110\0"+
    "\1\75\1\71\104\0\1\76\105\0\1\77\77\0\4\34"+
    "\5\0\13\34\4\0\30\34\26\0\4\34\5\0\7\34"+
    "\1\100\3\34\4\0\20\34\1\100\7\34\26\0\4\34"+
    "\5\0\7\34\1\101\3\34\4\0\20\34\1\101\7\34"+
    "\26\0\4\34\5\0\13\34\4\0\13\34\1\102\1\34"+
    "\1\103\3\34\1\104\6\34\26\0\4\34\5\0\13\34"+
    "\4\0\4\34\1\105\3\34\1\106\17\34\26\0\4\34"+
    "\5\0\13\34\4\0\26\34\1\107\1\34\26\0\4\34"+
    "\5\0\13\34\4\0\1\110\7\34\1\111\7\34\1\112"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\1\113\27\34"+
    "\26\0\4\34\5\0\13\34\4\0\14\34\1\114\1\115"+
    "\3\34\1\116\6\34\26\0\4\34\5\0\13\34\4\0"+
    "\1\117\7\34\1\120\17\34\26\0\4\34\5\0\13\34"+
    "\4\0\16\34\1\121\4\34\1\122\4\34\26\0\4\34"+
    "\5\0\7\34\1\101\3\34\4\0\1\34\1\123\16\34"+
    "\1\124\7\34\26\0\4\34\5\0\13\34\4\0\4\34"+
    "\1\125\23\34\26\0\4\34\5\0\13\34\4\0\7\34"+
    "\1\126\10\34\1\127\7\34\26\0\4\34\5\0\13\34"+
    "\4\0\17\34\1\130\10\34\26\0\4\34\5\0\13\34"+
    "\4\0\7\34\1\131\20\34\107\0\1\132\1\0\2\62"+
    "\1\0\2\62\1\0\4\62\1\0\35\62\1\0\35\62"+
    "\2\0\1\63\103\0\2\133\4\0\1\133\1\134\2\133"+
    "\1\135\10\133\2\136\1\137\22\133\1\140\3\133\1\141"+
    "\3\133\1\142\7\133\1\143\2\133\1\144\1\133\1\145"+
    "\10\133\2\67\1\0\2\67\1\0\1\67\1\0\40\67"+
    "\1\0\35\67\2\70\1\0\2\70\1\0\42\70\1\0"+
    "\1\70\1\0\33\70\15\146\1\147\70\146\2\74\1\6"+
    "\2\74\1\7\100\74\23\0\4\34\5\0\5\34\1\150"+
    "\5\34\4\0\16\34\1\150\11\34\26\0\4\34\5\0"+
    "\2\34\1\151\10\34\4\0\3\34\1\151\24\34\26\0"+
    "\4\34\5\0\13\34\4\0\13\34\1\152\14\34\26\0"+
    "\4\34\5\0\13\34\4\0\3\34\1\153\23\34\1\154"+
    "\26\0\4\34\5\0\13\34\4\0\2\34\1\155\25\34"+
    "\26\0\4\34\5\0\13\34\4\0\13\34\1\156\5\34"+
    "\1\157\6\34\26\0\4\34\5\0\13\34\4\0\21\34"+
    "\1\160\6\34\26\0\4\34\5\0\13\34\4\0\10\34"+
    "\1\161\6\34\1\162\10\34\26\0\4\34\5\0\13\34"+
    "\4\0\13\34\1\163\14\34\26\0\4\34\5\0\13\34"+
    "\4\0\20\34\1\164\7\34\26\0\4\34\5\0\13\34"+
    "\4\0\16\34\1\165\11\34\26\0\4\34\5\0\13\34"+
    "\4\0\24\34\1\166\3\34\26\0\4\34\5\0\13\34"+
    "\4\0\1\167\27\34\26\0\4\34\5\0\13\34\4\0"+
    "\21\34\1\170\6\34\26\0\4\34\5\0\13\34\4\0"+
    "\21\34\1\171\6\34\26\0\4\34\5\0\13\34\4\0"+
    "\12\34\1\172\1\34\1\173\13\34\26\0\4\34\5\0"+
    "\13\34\4\0\22\34\1\174\5\34\26\0\4\34\5\0"+
    "\13\34\4\0\13\34\1\175\14\34\26\0\4\34\5\0"+
    "\13\34\4\0\11\34\1\176\16\34\26\0\4\34\5\0"+
    "\13\34\4\0\13\34\1\177\6\34\1\200\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\10\34\1\201\17\34\26\0"+
    "\4\34\5\0\13\34\4\0\23\34\1\202\4\34\26\0"+
    "\4\34\5\0\13\34\4\0\3\34\1\203\24\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\204\23\34\26\0"+
    "\3\137\103\0\3\205\60\0\15\146\1\206\70\146\15\0"+
    "\1\147\4\0\1\6\106\0\4\34\5\0\11\34\1\207"+
    "\1\34\4\0\23\34\1\207\4\34\26\0\4\34\5\0"+
    "\3\34\1\210\7\34\4\0\4\34\1\210\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\211\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\2\34\1\212\25\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\213\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\21\34\1\214\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\20\34\1\215\7\34\26\0"+
    "\4\34\5\0\13\34\4\0\21\34\1\216\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\21\34\1\217\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\14\34\1\220\13\34\26\0"+
    "\4\34\5\0\13\34\4\0\10\34\1\221\17\34\26\0"+
    "\4\34\5\0\13\34\4\0\6\34\1\222\21\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\223\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\224\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\225\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\10\34\1\226\17\34\26\0"+
    "\4\34\5\0\13\34\4\0\13\34\1\227\14\34\26\0"+
    "\4\34\5\0\10\34\1\230\2\34\4\0\30\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\231\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\21\34\1\232\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\233\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\1\234\27\34\26\0\4\34"+
    "\5\0\13\34\4\0\20\34\1\235\7\34\3\0\15\146"+
    "\1\206\4\146\1\6\63\146\23\0\4\34\5\0\6\34"+
    "\1\236\4\34\4\0\17\34\1\236\10\34\26\0\4\34"+
    "\5\0\7\34\1\237\3\34\4\0\20\34\1\237\7\34"+
    "\26\0\4\34\5\0\13\34\4\0\22\34\1\240\5\34"+
    "\26\0\4\34\5\0\13\34\4\0\10\34\1\241\17\34"+
    "\26\0\4\34\5\0\13\34\4\0\22\34\1\242\5\34"+
    "\26\0\4\34\1\243\4\0\13\34\4\0\30\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\244\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\245\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\15\34\1\246\12\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\247\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\20\34\1\250\7\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\251\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\21\34\1\252\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\253\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\2\34\1\254\25\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\255\5\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\256\23\34\4\0"+
    "\2\257\1\0\2\257\15\0\4\34\5\0\13\34\4\0"+
    "\30\34\4\0\2\260\1\0\2\260\15\0\4\34\5\0"+
    "\13\34\4\0\30\34\26\0\4\34\5\0\13\34\4\0"+
    "\4\34\1\261\23\34\26\0\4\34\5\0\13\34\4\0"+
    "\15\34\1\262\12\34\26\0\4\34\5\0\13\34\4\0"+
    "\21\34\1\263\6\34\34\0\1\264\77\0\4\34\5\0"+
    "\13\34\4\0\6\34\1\265\21\34\26\0\4\34\5\0"+
    "\13\34\4\0\22\34\1\266\5\34\26\0\4\34\5\0"+
    "\13\34\4\0\1\267\27\34\26\0\4\34\5\0\13\34"+
    "\4\0\22\34\1\270\5\34\26\0\4\34\5\0\13\34"+
    "\4\0\4\34\1\271\23\34\4\0\2\257\1\0\2\257"+
    "\27\0\1\272\16\0\1\272\32\0\2\260\1\0\2\260"+
    "\27\0\1\273\16\0\1\273\54\0\4\34\5\0\13\34"+
    "\4\0\2\34\1\274\25\34\26\0\4\34\5\0\13\34"+
    "\4\0\22\34\1\275\5\34\51\0\1\276\33\0\1\276"+
    "\51\0\1\277\33\0\1\277\26\0\4\34\5\0\13\34"+
    "\4\0\22\34\1\300\5\34\26\0\4\34\5\0\13\34"+
    "\4\0\4\34\1\301\23\34\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8750];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\2\1\2\11\1\1\10\11\1\1\1\11"+
    "\1\1\1\11\3\1\1\11\3\1\3\11\15\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\3\1\2\11"+
    "\1\0\1\1\3\11\32\1\4\11\2\1\6\11\2\0"+
    "\35\1\1\11\1\0\34\1\1\0\13\1\2\0\3\1"+
    "\1\11\5\1\2\0\2\1\2\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuilder string = new StringBuilder();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ExpressionLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ExpressionSymbols.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
          // fall through
          case 77: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 78: break;
          case 3:
            { return symbol(NOT);
            }
          // fall through
          case 79: break;
          case 4:
            { yybegin(STRING_DOUBLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 80: break;
          case 5:
            { return symbol(DOLLAR);
            }
          // fall through
          case 81: break;
          case 6:
            { yybegin(STRING_SINGLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 82: break;
          case 7:
            { return symbol(LPAREN);
            }
          // fall through
          case 83: break;
          case 8:
            { return symbol(RPAREN);
            }
          // fall through
          case 84: break;
          case 9:
            { return symbol(MULT);
            }
          // fall through
          case 85: break;
          case 10:
            { return symbol(PLUS);
            }
          // fall through
          case 86: break;
          case 11:
            { return symbol(COMMA);
            }
          // fall through
          case 87: break;
          case 12:
            { return symbol(MINUS);
            }
          // fall through
          case 88: break;
          case 13:
            { return symbol(DOT);
            }
          // fall through
          case 89: break;
          case 14:
            { return symbol(DIV);
            }
          // fall through
          case 90: break;
          case 15:
            { return symbol(NUMBER, Integer.valueOf(yytext()));
            }
          // fall through
          case 91: break;
          case 16:
            { return symbol(COLON);
            }
          // fall through
          case 92: break;
          case 17:
            { return symbol(LT);
            }
          // fall through
          case 93: break;
          case 18:
            { return symbol(EQ);
            }
          // fall through
          case 94: break;
          case 19:
            { return symbol(GT);
            }
          // fall through
          case 95: break;
          case 20:
            { return symbol(QUESTION);
            }
          // fall through
          case 96: break;
          case 21:
            { return symbol(IDENTIFIER, yytext());
            }
          // fall through
          case 97: break;
          case 22:
            { return symbol(LBRACK);
            }
          // fall through
          case 98: break;
          case 23:
            { return symbol(RBRACK);
            }
          // fall through
          case 99: break;
          case 24:
            { yybegin(STRING_GRAVE_ACCENT); string.setLength(0);
            }
          // fall through
          case 100: break;
          case 25:
            { return symbol(LCURLY);
            }
          // fall through
          case 101: break;
          case 26:
            { return symbol(RCURLY);
            }
          // fall through
          case 102: break;
          case 27:
            { string.append( yytext() );
            }
          // fall through
          case 103: break;
          case 28:
            { throw new RuntimeException("Unterminated string at end of line");
            }
          // fall through
          case 104: break;
          case 29:
            { yybegin(YYINITIAL); return symbol(STRING, string.toString());
            }
          // fall through
          case 105: break;
          case 30:
            { return symbol(NOTEQ);
            }
          // fall through
          case 106: break;
          case 31:
            { return symbol(AND);
            }
          // fall through
          case 107: break;
          case 32:
            { return symbol(LTEQ);
            }
          // fall through
          case 108: break;
          case 33:
            { return symbol(EQEQ);
            }
          // fall through
          case 109: break;
          case 34:
            { return symbol(GTEQ);
            }
          // fall through
          case 110: break;
          case 35:
            { return symbol(AS);
            }
          // fall through
          case 111: break;
          case 36:
            { return symbol(IN);
            }
          // fall through
          case 112: break;
          case 37:
            { return symbol(IS);
            }
          // fall through
          case 113: break;
          case 38:
            { return symbol(OR);
            }
          // fall through
          case 114: break;
          case 39:
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          // fall through
          case 115: break;
          case 40:
            { string.append( '\"' );
            }
          // fall through
          case 116: break;
          case 41:
            { string.append( '\'' );
            }
          // fall through
          case 117: break;
          case 42:
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
            }
          // fall through
          case 118: break;
          case 43:
            { string.append( '\\' );
            }
          // fall through
          case 119: break;
          case 44:
            { string.append( '\b' );
            }
          // fall through
          case 120: break;
          case 45:
            { string.append( '\f' );
            }
          // fall through
          case 121: break;
          case 46:
            { string.append( '\n' );
            }
          // fall through
          case 122: break;
          case 47:
            { string.append( '\r' );
            }
          // fall through
          case 123: break;
          case 48:
            { string.append( '\t' );
            }
          // fall through
          case 124: break;
          case 49:
            { return symbol(ALL);
            }
          // fall through
          case 125: break;
          case 50:
            { return symbol(ANY);
            }
          // fall through
          case 126: break;
          case 51:
            { return symbol(ASC);
            }
          // fall through
          case 127: break;
          case 52:
            { return symbol(SET);
            }
          // fall through
          case 128: break;
          case 53:
            { return symbol(DESC);
            }
          // fall through
          case 129: break;
          case 54:
            { return symbol(FROM);
            }
          // fall through
          case 130: break;
          case 55:
            { return symbol(LAST);
            }
          // fall through
          case 131: break;
          case 56:
            { return symbol(LIKE);
            }
          // fall through
          case 132: break;
          case 57:
            { return symbol(NULL);
            }
          // fall through
          case 133: break;
          case 58:
            { return symbol(THIS);
            }
          // fall through
          case 134: break;
          case 59:
            { return symbol(BOOLEAN, Boolean.TRUE);
            }
          // fall through
          case 135: break;
          case 60:
            { return symbol(BOOLEAN, Boolean.FALSE);
            }
          // fall through
          case 136: break;
          case 61:
            { return symbol(FIRST);
            }
          // fall through
          case 137: break;
          case 62:
            { return symbol(IMAGE);
            }
          // fall through
          case 138: break;
          case 63:
            { return symbol(LIMIT);
            }
          // fall through
          case 139: break;
          case 64:
            { return symbol(NULLS);
            }
          // fall through
          case 140: break;
          case 65:
            { return symbol(WHERE);
            }
          // fall through
          case 141: break;
          case 66:
            { return symbol(DELETE);
            }
          // fall through
          case 142: break;
          case 67:
            { return symbol(EXISTS);
            }
          // fall through
          case 143: break;
          case 68:
            { return symbol(EXPR_START);
            }
          // fall through
          case 144: break;
          case 69:
            { return symbol(HAVING);
            }
          // fall through
          case 145: break;
          case 70:
            { return symbol(INSERT);
            }
          // fall through
          case 146: break;
          case 71:
            { return symbol(SELECT);
            }
          // fall through
          case 147: break;
          case 72:
            { return symbol(UPDATE);
            }
          // fall through
          case 148: break;
          case 73:
            { return symbol(GROUP_BY);
            }
          // fall through
          case 149: break;
          case 74:
            { return symbol(ORDER_BY);
            }
          // fall through
          case 150: break;
          case 75:
            { return symbol(DISTINCT);
            }
          // fall through
          case 151: break;
          case 76:
            { return symbol(OBJ_STATE);
            }
          // fall through
          case 152: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
