// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/dev/webfx/stack/orm/expression/parser/jflex/ExpressionLexer.flex


/* --------------------------Usercode Section------------------------ */

package dev.webfx.stack.orm.expression.parser.jflex;

import java_cup.runtime.*;
import        dev.webfx.stack.orm.expression.parser.javacup.ExpressionSymbols;
import static dev.webfx.stack.orm.expression.parser.javacup.ExpressionSymbols.*;


@SuppressWarnings("fallthrough")
public class ExpressionLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_SINGLE_QUOTE = 2;
  public static final int STRING_DOUBLE_QUOTE = 4;
  public static final int STRING_GRAVE_ACCENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\0\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\3\24\4\25\2\26\1\27\1\0\1\30\1\31\1\32"+
    "\1\33\1\0\1\34\1\35\1\34\1\36\1\37\1\34"+
    "\1\40\7\34\1\41\1\42\1\34\1\43\1\44\1\34"+
    "\1\45\3\34\1\46\1\34\1\47\1\50\1\51\1\0"+
    "\1\34\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\34\1\73\1\74\1\75\1\76\1\77"+
    "\1\100\1\101\1\102\1\103\1\104\1\105\1\106\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\17\1\20\1\21\1\22\1\23\1\24\3\25\1\26"+
    "\1\27\1\30\16\25\1\31\1\1\1\32\1\33\2\34"+
    "\1\35\1\1\2\33\1\36\1\37\1\40\1\0\1\2"+
    "\1\41\1\42\1\43\1\44\4\25\1\45\10\25\1\46"+
    "\1\47\7\25\1\50\7\25\1\50\1\51\1\52\1\53"+
    "\2\54\1\55\1\56\1\57\1\60\1\61\1\62\2\0"+
    "\2\25\1\63\1\37\1\64\1\65\20\25\1\3\4\25"+
    "\1\66\6\25\1\54\1\0\3\25\1\67\5\25\1\70"+
    "\3\25\1\71\1\25\1\72\2\25\1\73\3\25\1\74"+
    "\1\75\3\25\1\76\5\25\1\0\1\77\1\100\1\25"+
    "\1\101\2\25\1\102\1\25\1\103\3\25\1\104\1\25"+
    "\1\105\2\0\1\106\1\25\1\107\1\110\1\111\1\112"+
    "\3\25\1\113\1\114\1\115\2\0\1\25\1\116\2\25"+
    "\1\117\1\120\1\121\1\25\1\122\3\25\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\u011c\0\u0163\0\u01aa"+
    "\0\u011c\0\u011c\0\u01f1\0\u011c\0\u011c\0\u011c\0\u011c\0\u011c"+
    "\0\u011c\0\u011c\0\u0238\0\u027f\0\u011c\0\u02c6\0\u030d\0\u0354"+
    "\0\u039b\0\u03e2\0\u0238\0\u0429\0\u0470\0\u04b7\0\u011c\0\u011c"+
    "\0\u011c\0\u04fe\0\u0545\0\u058c\0\u05d3\0\u061a\0\u0661\0\u06a8"+
    "\0\u06ef\0\u0736\0\u077d\0\u07c4\0\u080b\0\u0852\0\u0899\0\u011c"+
    "\0\u08e0\0\u011c\0\u0927\0\u011c\0\u096e\0\u011c\0\u09b5\0\u09fc"+
    "\0\u0a43\0\u011c\0\u011c\0\u011c\0\u0a8a\0\u0ad1\0\u011c\0\u011c"+
    "\0\u011c\0\u011c\0\u0b18\0\u0b5f\0\u0ba6\0\u0bed\0\u0c34\0\u0c7b"+
    "\0\u0cc2\0\u0d09\0\u0d50\0\u0d97\0\u0dde\0\u0e25\0\u0e6c\0\u0eb3"+
    "\0\u0429\0\u0efa\0\u0f41\0\u0f88\0\u0fcf\0\u1016\0\u105d\0\u10a4"+
    "\0\u0b5f\0\u10eb\0\u1132\0\u1179\0\u11c0\0\u1207\0\u124e\0\u1295"+
    "\0\u011c\0\u011c\0\u011c\0\u011c\0\u12dc\0\u1323\0\u011c\0\u011c"+
    "\0\u011c\0\u011c\0\u011c\0\u011c\0\u136a\0\u13b1\0\u13f8\0\u143f"+
    "\0\u0429\0\u0429\0\u0429\0\u0429\0\u1486\0\u14cd\0\u1514\0\u155b"+
    "\0\u15a2\0\u15e9\0\u1630\0\u1677\0\u16be\0\u1705\0\u174c\0\u1793"+
    "\0\u17da\0\u1821\0\u1868\0\u18af\0\u0429\0\u18f6\0\u193d\0\u1984"+
    "\0\u19cb\0\u0429\0\u1a12\0\u1a59\0\u1aa0\0\u1ae7\0\u1b2e\0\u1b75"+
    "\0\u011c\0\u1bbc\0\u1c03\0\u1c4a\0\u1c91\0\u0429\0\u1cd8\0\u1d1f"+
    "\0\u1d66\0\u1dad\0\u1df4\0\u0429\0\u1e3b\0\u1e82\0\u1ec9\0\u0429"+
    "\0\u1f10\0\u0429\0\u1f57\0\u1f9e\0\u1fe5\0\u202c\0\u2073\0\u20ba"+
    "\0\u0429\0\u0429\0\u2101\0\u2148\0\u218f\0\u0429\0\u21d6\0\u221d"+
    "\0\u2264\0\u22ab\0\u22f2\0\u2339\0\u0429\0\u0429\0\u2380\0\u0429"+
    "\0\u23c7\0\u240e\0\u0429\0\u2455\0\u0429\0\u249c\0\u24e3\0\u252a"+
    "\0\u0429\0\u2571\0\u0429\0\u25b8\0\u25ff\0\u0429\0\u2646\0\u0429"+
    "\0\u011c\0\u0429\0\u0429\0\u268d\0\u26d4\0\u271b\0\u0429\0\u0429"+
    "\0\u0429\0\u2762\0\u27a9\0\u27f0\0\u0429\0\u2837\0\u287e\0\u011c"+
    "\0\u011c\0\u0429\0\u28c5\0\u0429\0\u290c\0\u2953\0\u299a\0\u0429";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\3\26\1\27\1\30\1\31\1\32"+
    "\1\33\4\34\1\35\1\36\5\34\1\37\1\5\1\40"+
    "\1\41\1\42\2\34\1\43\1\44\1\45\1\35\1\46"+
    "\1\47\2\34\1\50\1\51\1\52\1\53\2\34\1\54"+
    "\1\55\1\56\1\34\1\57\3\34\1\60\1\61\1\62"+
    "\2\63\1\64\2\63\1\65\4\63\1\66\35\63\1\67"+
    "\36\63\2\70\1\64\2\70\1\65\1\70\1\66\40\70"+
    "\1\67\36\70\2\71\1\64\2\71\1\65\42\71\1\67"+
    "\1\71\1\66\34\71\111\0\1\6\135\0\1\72\66\0"+
    "\1\73\116\0\1\74\102\0\1\75\4\0\1\76\107\0"+
    "\4\26\107\0\1\77\110\0\1\100\1\72\105\0\1\101"+
    "\106\0\1\102\100\0\4\34\5\0\13\34\4\0\31\34"+
    "\26\0\4\34\5\0\7\34\1\103\3\34\4\0\20\34"+
    "\1\103\10\34\26\0\4\34\5\0\7\34\1\104\3\34"+
    "\4\0\20\34\1\104\10\34\26\0\4\34\5\0\13\34"+
    "\4\0\13\34\1\105\1\34\1\106\3\34\1\107\7\34"+
    "\26\0\4\34\5\0\13\34\4\0\4\34\1\110\3\34"+
    "\1\111\20\34\26\0\4\34\5\0\13\34\4\0\26\34"+
    "\1\112\2\34\26\0\4\34\5\0\13\34\4\0\1\113"+
    "\7\34\1\114\7\34\1\115\10\34\26\0\4\34\5\0"+
    "\13\34\4\0\1\116\30\34\26\0\4\34\5\0\13\34"+
    "\4\0\14\34\1\117\1\120\3\34\1\121\7\34\26\0"+
    "\4\34\5\0\13\34\4\0\1\122\7\34\1\123\20\34"+
    "\26\0\4\34\5\0\13\34\4\0\1\124\30\34\26\0"+
    "\4\34\5\0\13\34\4\0\16\34\1\125\4\34\1\126"+
    "\5\34\26\0\4\34\5\0\7\34\1\104\3\34\4\0"+
    "\1\34\1\127\3\34\1\130\12\34\1\131\10\34\26\0"+
    "\4\34\5\0\13\34\4\0\4\34\1\132\24\34\26\0"+
    "\4\34\5\0\13\34\4\0\7\34\1\133\10\34\1\134"+
    "\10\34\26\0\4\34\5\0\13\34\4\0\15\34\1\135"+
    "\1\34\1\136\11\34\26\0\4\34\5\0\13\34\4\0"+
    "\7\34\1\137\1\140\20\34\110\0\1\141\1\0\2\63"+
    "\1\0\2\63\1\0\4\63\1\0\35\63\1\0\36\63"+
    "\2\0\1\64\104\0\2\142\4\0\1\142\1\143\2\142"+
    "\1\144\10\142\2\145\1\146\22\142\1\147\3\142\1\150"+
    "\3\142\1\151\7\142\1\152\2\142\1\153\1\142\1\154"+
    "\11\142\2\70\1\0\2\70\1\0\1\70\1\0\40\70"+
    "\1\0\36\70\2\71\1\0\2\71\1\0\42\71\1\0"+
    "\1\71\1\0\34\71\15\155\1\156\71\155\2\76\1\6"+
    "\2\76\1\7\101\76\23\0\4\34\5\0\5\34\1\157"+
    "\5\34\4\0\16\34\1\157\12\34\26\0\4\34\5\0"+
    "\2\34\1\160\10\34\4\0\3\34\1\160\25\34\26\0"+
    "\4\34\5\0\13\34\4\0\13\34\1\161\15\34\26\0"+
    "\4\34\5\0\13\34\4\0\3\34\1\162\23\34\1\163"+
    "\1\34\26\0\4\34\5\0\13\34\4\0\2\34\1\164"+
    "\26\34\26\0\4\34\5\0\13\34\4\0\13\34\1\165"+
    "\5\34\1\166\7\34\26\0\4\34\5\0\13\34\4\0"+
    "\21\34\1\167\7\34\26\0\4\34\5\0\13\34\4\0"+
    "\10\34\1\170\6\34\1\171\11\34\26\0\4\34\5\0"+
    "\13\34\4\0\13\34\1\172\15\34\26\0\4\34\5\0"+
    "\13\34\4\0\20\34\1\173\10\34\26\0\4\34\5\0"+
    "\13\34\4\0\16\34\1\174\12\34\26\0\4\34\5\0"+
    "\13\34\4\0\24\34\1\175\4\34\26\0\4\34\5\0"+
    "\13\34\4\0\1\176\30\34\26\0\4\34\5\0\13\34"+
    "\4\0\21\34\1\177\7\34\26\0\4\34\5\0\13\34"+
    "\4\0\21\34\1\200\1\201\6\34\26\0\4\34\5\0"+
    "\13\34\4\0\12\34\1\202\1\34\1\203\14\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\204\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\205\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\13\34\1\206\15\34\26\0"+
    "\4\34\5\0\13\34\4\0\11\34\1\207\17\34\26\0"+
    "\4\34\5\0\13\34\4\0\5\34\1\210\23\34\26\0"+
    "\4\34\5\0\13\34\4\0\13\34\1\211\6\34\1\212"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\10\34\1\213"+
    "\20\34\26\0\4\34\5\0\13\34\4\0\23\34\1\214"+
    "\5\34\26\0\4\34\5\0\13\34\4\0\10\34\1\215"+
    "\20\34\26\0\4\34\5\0\13\34\4\0\3\34\1\216"+
    "\25\34\26\0\4\34\5\0\13\34\4\0\4\34\1\217"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\22\34\1\220"+
    "\6\34\26\0\3\146\104\0\3\221\61\0\15\155\1\222"+
    "\71\155\15\0\1\156\4\0\1\6\107\0\4\34\5\0"+
    "\11\34\1\223\1\34\4\0\23\34\1\223\5\34\26\0"+
    "\4\34\5\0\3\34\1\224\7\34\4\0\4\34\1\224"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\4\34\1\225"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\2\34\1\226"+
    "\26\34\26\0\4\34\5\0\13\34\4\0\22\34\1\227"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\21\34\1\230"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\20\34\1\231"+
    "\10\34\26\0\4\34\5\0\13\34\4\0\21\34\1\232"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\21\34\1\233"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\14\34\1\234"+
    "\14\34\26\0\4\34\5\0\13\34\4\0\10\34\1\235"+
    "\20\34\26\0\4\34\5\0\13\34\4\0\6\34\1\236"+
    "\22\34\26\0\4\34\5\0\13\34\4\0\4\34\1\237"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\22\34\1\240"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\4\34\1\241"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\4\34\1\242"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\10\34\1\243"+
    "\20\34\26\0\4\34\5\0\13\34\4\0\4\34\1\244"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\13\34\1\245"+
    "\15\34\26\0\4\34\5\0\10\34\1\246\2\34\4\0"+
    "\31\34\26\0\4\34\5\0\13\34\4\0\21\34\1\247"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\4\34\1\250"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\21\34\1\251"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\4\34\1\252"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\16\34\1\253"+
    "\12\34\26\0\4\34\5\0\13\34\4\0\1\254\30\34"+
    "\26\0\4\34\5\0\13\34\4\0\20\34\1\255\10\34"+
    "\26\0\4\34\5\0\13\34\4\0\7\34\1\256\21\34"+
    "\3\0\15\155\1\222\4\155\1\6\64\155\23\0\4\34"+
    "\5\0\6\34\1\257\4\34\4\0\17\34\1\257\11\34"+
    "\26\0\4\34\5\0\7\34\1\260\3\34\4\0\20\34"+
    "\1\260\10\34\26\0\4\34\5\0\13\34\4\0\22\34"+
    "\1\261\6\34\26\0\4\34\5\0\13\34\4\0\10\34"+
    "\1\262\20\34\26\0\4\34\5\0\13\34\4\0\22\34"+
    "\1\263\6\34\26\0\4\34\1\264\4\0\13\34\4\0"+
    "\31\34\26\0\4\34\5\0\13\34\4\0\4\34\1\265"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\22\34\1\266"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\15\34\1\267"+
    "\13\34\26\0\4\34\5\0\13\34\4\0\4\34\1\270"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\20\34\1\271"+
    "\10\34\26\0\4\34\5\0\13\34\4\0\20\34\1\272"+
    "\10\34\26\0\4\34\5\0\13\34\4\0\22\34\1\273"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\20\34\1\274"+
    "\10\34\26\0\4\34\5\0\13\34\4\0\21\34\1\275"+
    "\7\34\26\0\4\34\5\0\13\34\4\0\22\34\1\276"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\4\34\1\277"+
    "\24\34\26\0\4\34\5\0\13\34\4\0\2\34\1\300"+
    "\26\34\26\0\4\34\5\0\13\34\4\0\15\34\1\301"+
    "\13\34\26\0\4\34\5\0\13\34\4\0\22\34\1\302"+
    "\6\34\26\0\4\34\5\0\13\34\4\0\4\34\1\303"+
    "\24\34\4\0\2\304\1\0\2\304\15\0\4\34\5\0"+
    "\13\34\4\0\31\34\4\0\2\305\1\0\2\305\15\0"+
    "\4\34\5\0\13\34\4\0\31\34\26\0\4\34\5\0"+
    "\13\34\4\0\4\34\1\306\24\34\26\0\4\34\5\0"+
    "\13\34\4\0\15\34\1\307\13\34\26\0\4\34\5\0"+
    "\13\34\4\0\21\34\1\310\7\34\34\0\1\311\100\0"+
    "\4\34\5\0\13\34\4\0\6\34\1\312\22\34\26\0"+
    "\4\34\5\0\13\34\4\0\22\34\1\313\6\34\26\0"+
    "\4\34\5\0\13\34\4\0\1\314\30\34\26\0\4\34"+
    "\5\0\13\34\4\0\10\34\1\315\20\34\26\0\4\34"+
    "\5\0\13\34\4\0\1\316\30\34\26\0\4\34\5\0"+
    "\13\34\4\0\22\34\1\317\6\34\26\0\4\34\5\0"+
    "\13\34\4\0\22\34\1\320\6\34\26\0\4\34\5\0"+
    "\13\34\4\0\4\34\1\321\24\34\4\0\2\304\1\0"+
    "\2\304\27\0\1\322\16\0\1\322\33\0\2\305\1\0"+
    "\2\305\27\0\1\323\16\0\1\323\55\0\4\34\5\0"+
    "\13\34\4\0\2\34\1\324\26\34\26\0\4\34\5\0"+
    "\13\34\4\0\13\34\1\325\15\34\26\0\4\34\5\0"+
    "\13\34\4\0\1\326\30\34\26\0\4\34\5\0\13\34"+
    "\4\0\22\34\1\327\6\34\51\0\1\330\33\0\1\330"+
    "\52\0\1\331\33\0\1\331\27\0\4\34\5\0\13\34"+
    "\4\0\22\34\1\332\6\34\26\0\4\34\5\0\13\34"+
    "\4\0\13\34\1\333\15\34\26\0\4\34\5\0\13\34"+
    "\4\0\4\34\1\334\24\34\26\0\4\34\5\0\13\34"+
    "\4\0\10\34\1\335\20\34\26\0\4\34\5\0\13\34"+
    "\4\0\30\34\1\336\26\0\4\34\5\0\13\34\4\0"+
    "\4\34\1\337\24\34\26\0\4\34\5\0\13\34\4\0"+
    "\3\34\1\340\25\34\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10721];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\2\1\2\11\1\1\7\11\2\1\1\11"+
    "\11\1\3\11\16\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\3\1\3\11\1\0\1\1\4\11\36\1"+
    "\4\11\2\1\6\11\2\0\42\1\1\11\1\0\41\1"+
    "\1\0\17\1\2\0\3\1\1\11\10\1\2\0\4\1"+
    "\2\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuilder string = new StringBuilder();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ExpressionLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ExpressionSymbols.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
          // fall through
          case 84: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 85: break;
          case 3:
            { return symbol(NOT);
            }
          // fall through
          case 86: break;
          case 4:
            { yybegin(STRING_DOUBLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 87: break;
          case 5:
            { return symbol(DOLLAR);
            }
          // fall through
          case 88: break;
          case 6:
            { yybegin(STRING_SINGLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 89: break;
          case 7:
            { return symbol(LPAREN);
            }
          // fall through
          case 90: break;
          case 8:
            { return symbol(RPAREN);
            }
          // fall through
          case 91: break;
          case 9:
            { return symbol(MULT);
            }
          // fall through
          case 92: break;
          case 10:
            { return symbol(PLUS);
            }
          // fall through
          case 93: break;
          case 11:
            { return symbol(COMMA);
            }
          // fall through
          case 94: break;
          case 12:
            { return symbol(MINUS);
            }
          // fall through
          case 95: break;
          case 13:
            { return symbol(DOT);
            }
          // fall through
          case 96: break;
          case 14:
            { return symbol(DIV);
            }
          // fall through
          case 97: break;
          case 15:
            { return symbol(NUMBER, Integer.valueOf(yytext()));
            }
          // fall through
          case 98: break;
          case 16:
            { return symbol(COLON);
            }
          // fall through
          case 99: break;
          case 17:
            { return symbol(LT);
            }
          // fall through
          case 100: break;
          case 18:
            { return symbol(EQ);
            }
          // fall through
          case 101: break;
          case 19:
            { return symbol(GT);
            }
          // fall through
          case 102: break;
          case 20:
            { return symbol(QUESTION);
            }
          // fall through
          case 103: break;
          case 21:
            { return symbol(IDENTIFIER, yytext());
            }
          // fall through
          case 104: break;
          case 22:
            { return symbol(LBRACK);
            }
          // fall through
          case 105: break;
          case 23:
            { return symbol(RBRACK);
            }
          // fall through
          case 106: break;
          case 24:
            { yybegin(STRING_GRAVE_ACCENT); string.setLength(0);
            }
          // fall through
          case 107: break;
          case 25:
            { return symbol(LCURLY);
            }
          // fall through
          case 108: break;
          case 26:
            { return symbol(RCURLY);
            }
          // fall through
          case 109: break;
          case 27:
            { string.append( yytext() );
            }
          // fall through
          case 110: break;
          case 28:
            { throw new RuntimeException("Unterminated string at end of line");
            }
          // fall through
          case 111: break;
          case 29:
            { yybegin(YYINITIAL); return symbol(STRING, string.toString());
            }
          // fall through
          case 112: break;
          case 30:
            { return symbol(NOTEQ);
            }
          // fall through
          case 113: break;
          case 31:
            { return symbol(AND);
            }
          // fall through
          case 114: break;
          case 32:
            { return symbol(QUESTION_DOT);
            }
          // fall through
          case 115: break;
          case 33:
            { return symbol(DOUBLE_COLON);
            }
          // fall through
          case 116: break;
          case 34:
            { return symbol(LTEQ);
            }
          // fall through
          case 117: break;
          case 35:
            { return symbol(EQEQ);
            }
          // fall through
          case 118: break;
          case 36:
            { return symbol(GTEQ);
            }
          // fall through
          case 119: break;
          case 37:
            { return symbol(AS);
            }
          // fall through
          case 120: break;
          case 38:
            { return symbol(IN);
            }
          // fall through
          case 121: break;
          case 39:
            { return symbol(IS);
            }
          // fall through
          case 122: break;
          case 40:
            { return symbol(OR);
            }
          // fall through
          case 123: break;
          case 41:
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          // fall through
          case 124: break;
          case 42:
            { string.append( '\"' );
            }
          // fall through
          case 125: break;
          case 43:
            { string.append( '\'' );
            }
          // fall through
          case 126: break;
          case 44:
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
            }
          // fall through
          case 127: break;
          case 45:
            { string.append( '\\' );
            }
          // fall through
          case 128: break;
          case 46:
            { string.append( '\b' );
            }
          // fall through
          case 129: break;
          case 47:
            { string.append( '\f' );
            }
          // fall through
          case 130: break;
          case 48:
            { string.append( '\n' );
            }
          // fall through
          case 131: break;
          case 49:
            { string.append( '\r' );
            }
          // fall through
          case 132: break;
          case 50:
            { string.append( '\t' );
            }
          // fall through
          case 133: break;
          case 51:
            { return symbol(ALL);
            }
          // fall through
          case 134: break;
          case 52:
            { return symbol(ANY);
            }
          // fall through
          case 135: break;
          case 53:
            { return symbol(ASC);
            }
          // fall through
          case 136: break;
          case 54:
            { return symbol(SET);
            }
          // fall through
          case 137: break;
          case 55:
            { return symbol(DESC);
            }
          // fall through
          case 138: break;
          case 56:
            { return symbol(FROM);
            }
          // fall through
          case 139: break;
          case 57:
            { return symbol(LAST);
            }
          // fall through
          case 140: break;
          case 58:
            { return symbol(LIKE);
            }
          // fall through
          case 141: break;
          case 59:
            { return symbol(NULL);
            }
          // fall through
          case 142: break;
          case 60:
            { return symbol(THIS);
            }
          // fall through
          case 143: break;
          case 61:
            { return symbol(BOOLEAN, Boolean.TRUE);
            }
          // fall through
          case 144: break;
          case 62:
            { return symbol(WITH);
            }
          // fall through
          case 145: break;
          case 63:
            { return symbol(BOOLEAN, Boolean.FALSE);
            }
          // fall through
          case 146: break;
          case 64:
            { return symbol(FIRST);
            }
          // fall through
          case 147: break;
          case 65:
            { return symbol(IMAGE);
            }
          // fall through
          case 148: break;
          case 66:
            { return symbol(LIMIT);
            }
          // fall through
          case 149: break;
          case 67:
            { return symbol(NULLS);
            }
          // fall through
          case 150: break;
          case 68:
            { return symbol(UNION);
            }
          // fall through
          case 151: break;
          case 69:
            { return symbol(WHERE);
            }
          // fall through
          case 152: break;
          case 70:
            { return symbol(DELETE);
            }
          // fall through
          case 153: break;
          case 71:
            { return symbol(EXISTS);
            }
          // fall through
          case 154: break;
          case 72:
            { return symbol(EXPR_START);
            }
          // fall through
          case 155: break;
          case 73:
            { return symbol(HAVING);
            }
          // fall through
          case 156: break;
          case 74:
            { return symbol(INSERT);
            }
          // fall through
          case 157: break;
          case 75:
            { return symbol(OFFSET);
            }
          // fall through
          case 158: break;
          case 76:
            { return symbol(SELECT);
            }
          // fall through
          case 159: break;
          case 77:
            { return symbol(UPDATE);
            }
          // fall through
          case 160: break;
          case 78:
            { return symbol(LATERAL);
            }
          // fall through
          case 161: break;
          case 79:
            { return symbol(GROUP_BY);
            }
          // fall through
          case 162: break;
          case 80:
            { return symbol(ORDER_BY);
            }
          // fall through
          case 163: break;
          case 81:
            { return symbol(DISTINCT);
            }
          // fall through
          case 164: break;
          case 82:
            { return symbol(OBJ_STATE);
            }
          // fall through
          case 165: break;
          case 83:
            { return symbol(MATERIALIZED);
            }
          // fall through
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
