package dev.webfx.stack.session.state;

import dev.webfx.platform.util.Booleans;
import dev.webfx.stack.session.Session;

import java.util.Objects;

/**
 * @author Bruno Salmon
 */
public final class SessionAccessor {

    private final static String SERVER_SESSION_ID_ATTRIBUE_NAME = "serverSessionId"; // Used only on the client side to store the sessionId generated by the server
    private final static String USER_ID_ATTRIBUE_NAME = "userId";
    private final static String USER_TOKEN_ATTRIBUE_NAME = "userToken"; // The server's signed statement of who the user is, held by the client and echoed back
    private final static String RUN_ID_ATTRIBUE_NAME = "runId"; // Used only on the server side to store the runId generated by the client
    private final static String BACKOFFICE_ATTRIBUE_NAME = "backoffice"; // Used only on the server side to store the client type (backoffice or not)
    private final static String CLIENT_VERSION_ATTRIBUE_NAME = "clientVersion"; // Server-side: invariant client build id, sent once at connection
    private final static String PWA_ATTRIBUE_NAME = "pwa"; // Server-side: whether the client runs as an installed PWA, sent once at connection
    private final static String CLIENT_PROFILE_ATTRIBUE_NAME = "clientProfile"; // Server-side: compact "browser|os|deviceType" profile, sent once at connection
    private final static String SERVER_SESSION_ID_SYNCED_ATTRIBUE_NAME = "serverSessionIdSynced"; // Used only on the server side to store the info if the client knows the sessionId


    public static String getServerSessionId(Session session) {
        return session.get(SERVER_SESSION_ID_ATTRIBUE_NAME);
    }

    public static boolean changeServerSessionId(Session session, String sessionId, boolean skipNullValue) {
        return changeSessionAttribute(session, SERVER_SESSION_ID_ATTRIBUE_NAME, sessionId, skipNullValue);
    }

    public static Object getUserId(Session session) {
        return session.get(USER_ID_ATTRIBUE_NAME);
    }

    public static boolean changeUserId(Session session, Object userId, boolean skipNullValue) {
        return changeSessionAttribute(session, USER_ID_ATTRIBUE_NAME, userId, skipNullValue);
    }

    public static String getUserToken(Session session) {
        return (String) session.get(USER_TOKEN_ATTRIBUE_NAME);
    }

    public static boolean changeUserToken(Session session, String userToken, boolean skipNullValue) {
        return changeSessionAttribute(session, USER_TOKEN_ATTRIBUE_NAME, userToken, skipNullValue);
    }

    public static String getRunId(Session session) {
        return session.get(RUN_ID_ATTRIBUE_NAME);
    }

    public static boolean changeRunId(Session session, String runId, boolean skipNullValue) {
        return changeSessionAttribute(session, RUN_ID_ATTRIBUE_NAME, runId, skipNullValue);
    }

    public static Boolean isBackoffice(Session session) {
        return Booleans.toBoolean(session.get(BACKOFFICE_ATTRIBUE_NAME));
    }

    public static boolean changeBackoffice(Session session, Boolean backoffice, boolean skipNullValue) {
        return changeSessionAttribute(session, BACKOFFICE_ATTRIBUE_NAME, backoffice, skipNullValue);
    }

    public static String getClientVersion(Session session) {
        return session.get(CLIENT_VERSION_ATTRIBUE_NAME);
    }

    public static boolean changeClientVersion(Session session, String clientVersion, boolean skipNullValue) {
        return changeSessionAttribute(session, CLIENT_VERSION_ATTRIBUE_NAME, clientVersion, skipNullValue);
    }

    public static Boolean getPwa(Session session) {
        return Booleans.toBoolean(session.get(PWA_ATTRIBUE_NAME));
    }

    public static boolean changePwa(Session session, Boolean pwa, boolean skipNullValue) {
        return changeSessionAttribute(session, PWA_ATTRIBUE_NAME, pwa, skipNullValue);
    }

    public static String getClientProfile(Session session) {
        return session.get(CLIENT_PROFILE_ATTRIBUE_NAME);
    }

    public static boolean changeClientProfile(Session session, String clientProfile, boolean skipNullValue) {
        return changeSessionAttribute(session, CLIENT_PROFILE_ATTRIBUE_NAME, clientProfile, skipNullValue);
    }

    public static boolean isServerSessionIdSynced(Session session) {
        return Boolean.TRUE.equals(session.get(SERVER_SESSION_ID_SYNCED_ATTRIBUE_NAME));
    }

    public static boolean changeServerSessionIdSynced(Session session, boolean serverSessionIdSynced) {
        return changeSessionAttribute(session, SERVER_SESSION_ID_SYNCED_ATTRIBUE_NAME, serverSessionIdSynced, false);
    }

    static boolean changeSessionAttribute(Session session, String key, Object value, boolean skipNullValue) {
        if (skipNullValue && value == null || session == null || Objects.equals(value, session.get(key)))
            return false;
        //System.out.println("session(" + session.id() + ")." + key + " = " + value);
        if (value == null)
            session.remove(key);
        else
            session.put(key, value);
        return true;
    }
}
