package dev.webfx.stack.orm.dql.sqlcompiler.sql;

import dev.webfx.stack.orm.expression.Expression;
import dev.webfx.stack.orm.expression.terms.As;
import dev.webfx.stack.orm.dql.sqlcompiler.lci.CompilerDomainModelReader;
import dev.webfx.stack.orm.dql.sqlcompiler.sql.dbms.DbmsSqlSyntax;
import dev.webfx.stack.orm.dql.sqlcompiler.sql.dbms.HsqlSyntax;
import dev.webfx.stack.orm.dql.sqlcompiler.terms.Options;
import dev.webfx.stack.orm.dql.sqlcompiler.mapping.QueryColumnToEntityFieldMapping;
import dev.webfx.stack.orm.dql.sqlcompiler.mapping.QueryRowToEntityMapping;
import dev.webfx.platform.util.Numbers;
import dev.webfx.platform.util.Strings;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


/**
 * @author Bruno Salmon
 */
public final class SqlBuild {
    /**
     * Final fields built by SQL compilation to generate a SqlCompiled object **
     */
    private String sql;
    private boolean isQuery;
    private String[] autoGeneratedKeyColumnNames;
    private String countSql; // select count(*) ... used to return the total row numbers when the query is truncated by the limit clause

    private final Object selectDomainClass;
    private final ArrayList<QueryColumnToEntityFieldMapping> columnMappings = new ArrayList<>(); // first one = id column

    private Expression<?> sqlUncompilableCondition;
    private boolean cacheable = true;

    /**
     * Temporary fields used during SQL compilation **
     */
    private final SqlBuild parent;
    private final String tableAlias;
    private Object compilingClass;
    private String compilingTableAlias;
    private QueryColumnToEntityFieldMapping leftJoinMapping;
    private final DbmsSqlSyntax dbmsSyntax;

    private boolean distinct;

    private final HashMap<SqlClause, StringBuilder> sqlClauseBuilders = new HashMap<>();
    private final HashMap<String /* table alias */, Map<Join, Join> /* joins */ > joins = new HashMap<>();

    private final HashMap<String, String> tableAliases = new HashMap<>();   // tableAlias => tableName (real SQL table or CTE alias for field resolution)
    private HashMap<String, String> cteAliasTableNames = null; // tableAlias => CTE name (overrides tableAliases for SQL generation)
    private HashMap<String, String> logicalAliases = null; // logicalAlias => sqlAlias
    private HashMap<String, String> lateralSqlMap = null; // alias => compiled SQL of the lateral subquery
    private final List<String> orderedAliases = new ArrayList<>();
    private final HashMap<String, QueryColumnToEntityFieldMapping> fullColumnNameToColumnMappings = new HashMap<>(); // tableAlias.columnName => columnMapping
    //private int fromTablesCount;
    private final List<String> parameterNames;
    public int parameterIndex;

    public SqlBuild(SqlBuild parent, Object selectDomainClass, String tableAlias, SqlClause clause, DbmsSqlSyntax dbmsSyntax, CompilerDomainModelReader modelReader) {
        this.parent = parent;
        this.compilingClass = this.selectDomainClass = selectDomainClass;
        String tableName = modelReader.getDomainClassSqlTableName(selectDomainClass);
        this.compilingTableAlias = this.tableAlias = getNewTableAlias(tableName, tableAlias, false);
        this.dbmsSyntax = dbmsSyntax;
        this.parameterNames = parent == null ? new ArrayList<>() : parent.parameterNames;
        prepareAppend(clause, ""); // just for marking the clause
    }

    public Object getSelectDomainClass() {
        return selectDomainClass;
    }

    public DbmsSqlSyntax getDbmsSyntax() {
        return dbmsSyntax;
    }

    public List<String> getParameterNames() {
        return parameterNames;
    }

    public boolean hasParent() {
        return parent != null;
    }

    private SqlBuild getTopParent() {
        return parent == null ? this : parent.getTopParent();
    }

    public int incrementParameterIndex() {
        return ++getTopParent().parameterIndex;
    }

    public void setAutoGeneratedKeyColumnNames(String[] autoGeneratedKeyColumnNames) {
        this.autoGeneratedKeyColumnNames = autoGeneratedKeyColumnNames;
        if (autoGeneratedKeyColumnNames != null && dbmsSyntax == HsqlSyntax.get()) // HSQL error if not uppercase
            for (int i = 0; i < autoGeneratedKeyColumnNames.length; i++)
                autoGeneratedKeyColumnNames[i] = autoGeneratedKeyColumnNames[i].toUpperCase();
    }

    public Expression<?> getSqlUncompilableCondition() {
        return sqlUncompilableCondition;
    }

    public void setSqlUncompilableCondition(Expression<?> sqlUncompilableCondition) {
        this.sqlUncompilableCondition = sqlUncompilableCondition;
    }

    public void setCacheable(boolean cacheable) {
        this.cacheable = cacheable;
        if (!cacheable && parent != null)
            parent.setCacheable(false);
    }

    public boolean isCacheable() {
        return cacheable;
    }

    public String getTableAlias() {
        return tableAlias;
    }

    public SqlCompiled toSqlCompiled() {
        int n = columnMappings.size();
        QueryRowToEntityMapping queryMapping = null;
        if (n > 0) {
            QueryColumnToEntityFieldMapping[] nonIdColumnMappings = new QueryColumnToEntityFieldMapping[n - 1];
            for (int i = 1; i < n; i++)
                nonIdColumnMappings[i - 1] = columnMappings.get(i);
            queryMapping = new QueryRowToEntityMapping(0, selectDomainClass, nonIdColumnMappings);
        }
        return new SqlCompiled(toSql(), toCountSql(), parameterNames, isQuery, autoGeneratedKeyColumnNames, queryMapping, sqlUncompilableCondition, cacheable);
    }

    public String toSql() {
        if (sql == null) {
            StringBuilder sb = new StringBuilder();
            StringBuilder select = getClauseBuilder(SqlClause.SELECT);
            StringBuilder insert = getClauseBuilder(SqlClause.INSERT);
            isQuery = select != null;
            if (isQuery)
                sb.append("select ").append(_if(distinct, "distinct ")).append(select).append(" from ");
            else if (getClauseBuilder(SqlClause.UPDATE) != null)
                sb.append("update ");
            else if (insert != null)
                sb.append("insert into ");
            else if (getClauseBuilder(SqlClause.DELETE) != null)
                sb.append("delete ").append(_if(dbmsSyntax.repeatTableAliasAfterDelete(), tableAlias)).append(" from ");
            //sb.append(_if(fromTablesCount > 1, "(")); // select * from (t1, t2) join ... (marche pas avec postgres)
            boolean first = true;
            for (String tableAlias : orderedAliases) {
                if (!isJoinTableAlias(tableAlias)) {
                    // Check if this is a lateral subquery
                    if (lateralSqlMap != null && lateralSqlMap.containsKey(tableAlias)) {
                        sb.append(" cross join lateral (").append(lateralSqlMap.get(tableAlias)).append(") as ").append(tableAlias);
                        continue;
                    }
                    // Use CTE name if available (for SQL generation), otherwise use real table name
                    String tableName = (cteAliasTableNames != null && cteAliasTableNames.containsKey(tableAlias))
                            ? cteAliasTableNames.get(tableAlias)
                            : tableAliases.get(tableAlias);
                    if (!first)
                        sb.append(", ");
                    sb.append(dbmsSyntax.quoteTableIfReserved(tableName)); // tableName
                    if (insert == null) // no alias allowed in insert sql statement
                        sb.append(" as ").append(tableAlias); // may need ` as ` instead of ` ` for some dbms
                    first = false;
                    appendJoinsRecursively(tableAlias, sb); // depth-first: all sub-joins before the next base table
                }
            }
            sb//.append(_if(fromTablesCount > 1, ") "))
                    .append(_if(" set ", getClauseBuilder(SqlClause.UPDATE), "", sb))
                    .append(_if(" (", insert, ")", sb))
                    .append(_if(" values (", getClauseBuilder(SqlClause.VALUES), ")", sb))
                    .append(_if(" where ", getClauseBuilder(SqlClause.WHERE), "", sb))
                    .append(_if(" group by ", getClauseBuilder(SqlClause.GROUP_BY), "", sb))
                    .append(_if(" having ", getClauseBuilder(SqlClause.HAVING), "", sb))
                    .append(_if(" order by ", getClauseBuilder(SqlClause.ORDER_BY), "", sb))
                    .append(_if(" limit ", getClauseBuilder(SqlClause.LIMIT), "", sb))
                    .append(_if(" offset ", getClauseBuilder(SqlClause.OFFSET), "", sb))
                    .append(_if(" returning ", getClauseBuilder(SqlClause.RETURNING), "", sb));
            sql = sb.toString();
        }
        return sql;
    }

    public String toCountSql() {
        if (countSql == null) {
            StringBuilder sb = new StringBuilder();
            sb.append("select count(*) from ");
            boolean first = true;
            for (String tableAlias : orderedAliases) {
                if (!isJoinTableAlias(tableAlias)) {
                    String tableName = (cteAliasTableNames != null && cteAliasTableNames.containsKey(tableAlias))
                            ? cteAliasTableNames.get(tableAlias)
                            : tableAliases.get(tableAlias);
                    if (!first)
                        sb.append(", ");
                    sb.append(dbmsSyntax.quoteTableIfReserved(tableName)); // tableName
                    sb.append(" as ").append(tableAlias); // may need ` as ` instead of ` ` for some dbms
                    first = false;
                    appendJoinsRecursively(tableAlias, sb); // depth-first: all sub-joins before the next base table
                }
            }
            sb//.append(_if(fromTablesCount > 1, ") "))
                    .append(_if(" where ", getClauseBuilder(SqlClause.WHERE), "", sb))
                    .append(_if(" group by ", getClauseBuilder(SqlClause.GROUP_BY), "", sb))
                    .append(_if(" having ", getClauseBuilder(SqlClause.HAVING), "", sb));
            countSql = sb.toString();
        }
        return countSql;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public Object getCompilingClass() {
        return compilingClass;
    }

    public void setCompilingClass(Object compilingClass) {
        this.compilingClass = compilingClass;
    }

    public String getCompilingTableAlias() {
        return compilingTableAlias;
    }

    public void setCompilingTableAlias(String compilingTableAlias) {
        this.compilingTableAlias = compilingTableAlias;
    }

    public String getClassAlias(Object domainClass, CompilerDomainModelReader modelReader) {
        if  (domainClass == compilingClass)
            return compilingTableAlias;
        String tableName = modelReader.getDomainClassSqlTableName(domainClass);
        for (Map.Entry<String, String> entry : tableAliases.entrySet()) {
            if (tableName.equals(entry.getValue()))
                return entry.getKey();
        }
        if (parent != null)
            return parent.getClassAlias(domainClass, modelReader);
        return null;
    }

    public QueryColumnToEntityFieldMapping getLeftJoinMapping() {
        return leftJoinMapping;
    }

    public void setLeftJoinMapping(QueryColumnToEntityFieldMapping leftJoinMapping) {
        this.leftJoinMapping = leftJoinMapping;
    }

    private StringBuilder getClauseBuilder(SqlClause clause) {
        return sqlClauseBuilders.get(clause);
    }

    public int evaluateLimit() {
        StringBuilder limit = getClauseBuilder(SqlClause.LIMIT);
        return Strings.isEmpty(limit) ? -1 : Numbers.intValue(limit);
    }


    /* Building methods */

    public StringBuilder prepareAppend(Options o) {
        return prepareAppend(o.clause, o.separator);
    }

    public StringBuilder prepareAppend(SqlClause clause, String separator) {
        StringBuilder clauseBuilder = sqlClauseBuilders.computeIfAbsent(clause, k -> new StringBuilder());
        if (Strings.isNotEmpty(separator) && Strings.isNotEmpty(clauseBuilder) && !endsWith(clauseBuilder, separator) && !endsWith(clauseBuilder, "(") && !endsWith(clauseBuilder, "["))
            clauseBuilder.append(separator);
        return clauseBuilder;
    }

    private static boolean endsWith(StringBuilder sb, String s) {
        int sbLength = sb.length();
        int sLength = s.length();
        if (sLength == 0 || sbLength < sLength)
            return false;
        for (int i = 0; i < sLength; i++)
            if (sb.charAt(i + sbLength - sLength) != s.charAt(i))
                return false;
        return true;
    }

    private String getNewTableAlias(String tableName, String tableAlias, boolean join) {
        if (tableAlias == null) {
            char c = join ? 'j' : 't';
            StringBuilder sb = new StringBuilder();
            for (SqlBuild b = this; b != null; b = b.parent)
                sb.append(c);
            sb.append(tableAliases.size() + 1);
            tableAlias = sb.toString();
        }
        tableAliases.put(tableAlias, tableName);
        orderedAliases.add(tableAlias);
        return tableAlias;
    }

    private boolean isJoinTableAlias(String tableAlias) {
        return tableAlias.charAt(0) == 'j';
    }

    private SqlBuild getLogicalAliasBuild(String logicalAlias) {
        if (logicalAlias == null || logicalAlias.equals(tableAlias))
            return this;
        if (logicalAliases != null && logicalAliases.containsKey(logicalAlias))
            return this;
        if (parent != null)
            return parent.getLogicalAliasBuild(logicalAlias);
        return null;
    }

    public String getSqlAlias(String logicalAlias) {
        return getSqlAlias(logicalAlias, getLogicalAliasBuild(logicalAlias));
    }

    private String getSqlAlias(String logicalAlias, SqlBuild logicalAliasBuild) {
        String sqlAlias = null;
        if (logicalAliasBuild != null && logicalAliasBuild.logicalAliases != null)
            sqlAlias = logicalAliasBuild.logicalAliases.get(logicalAlias);
        return sqlAlias != null ? sqlAlias : logicalAlias;
    }

    private void recordLogicalAlias(String logicalAlias, String sqlAlias) {
        if (logicalAliases == null)
            logicalAliases = new HashMap<>();
        logicalAliases.put(logicalAlias, sqlAlias);
    }

    public boolean hasColumnMapping(String columnName) {
        return fullColumnNameToColumnMappings.containsKey(dbmsSyntax.quoteColumnIfReserved(columnName));
    }

    public QueryColumnToEntityFieldMapping addColumnInClause(String tableAlias, String columnName, Object fieldId, Object foreignFieldClassId, SqlClause clause, String separator, boolean grouped, boolean isBoolean, boolean generateQueryMapping) {
        if (clause == SqlClause.INSERT || clause == SqlClause.VALUES || clause == SqlClause.UPDATE /* Postgres doesn't like alias in set clause */)
            tableAlias = null;
        else
            tableAlias = getSqlAlias(tableAlias);
        String fullColumnName = dbmsSyntax.quoteColumnIfReserved(columnName);
        if (tableAlias != null)
            fullColumnName = tableAlias + '.' + fullColumnName;
        QueryColumnToEntityFieldMapping queryColumnToEntityFieldMapping = null;
        if (clause == SqlClause.SELECT) {
            queryColumnToEntityFieldMapping = fullColumnNameToColumnMappings.get(fullColumnName);
            if (queryColumnToEntityFieldMapping != null && generateQueryMapping) // doesn't append column except when not generateQueryMapping (ex: function call)
                fullColumnName = null;
            else if (generateQueryMapping) { // queryColumnToEntityFieldMapping is necessary null in this case
                fullColumnNameToColumnMappings.put(fullColumnName, queryColumnToEntityFieldMapping = new QueryColumnToEntityFieldMapping(fullColumnNameToColumnMappings.size(), fieldId, foreignFieldClassId, leftJoinMapping));
                columnMappings.add(queryColumnToEntityFieldMapping);
            }
        }
        if (fullColumnName != null) {
            if (grouped && (clause == SqlClause.SELECT || clause == SqlClause.ORDER_BY))
                fullColumnName = (isBoolean ? "first(" : "min(") + fullColumnName + ")"; // min is much faster (native) than first (written in SQL), but min doesn't work for boolean in postgres
            prepareAppend(clause, separator).append(fullColumnName);
        }
        return queryColumnToEntityFieldMapping;
    }

    private void appendJoinsRecursively(String tableAlias, StringBuilder sb) {
        Map<Join, Join> tableJoins = joins.get(tableAlias);
        if (tableJoins == null) return;
        Join.appendJoins(tableJoins, sb);
        for (Join join : tableJoins.keySet())
            appendJoinsRecursively(join.table2Alias, sb);
    }

    public void registerFromTable(String tableName, String tableAlias) {
        tableAliases.put(tableAlias, tableName);
        orderedAliases.add(tableAlias);
    }

    public void setCteTableName(String cteName) {
        if (cteAliasTableNames == null)
            cteAliasTableNames = new HashMap<>();
        cteAliasTableNames.put(tableAlias, cteName);
        // Register a logical alias so that Alias references using the CTE name (e.g. "ep") resolve to
        // the generated SQL table alias (e.g. "tt1"), ensuring JOINs are stored and emitted correctly.
        recordLogicalAlias(cteName, tableAlias);
    }

    public void registerCteFromTable(String cteName, String realTableName, String tableAlias) {
        tableAliases.put(tableAlias, realTableName); // real table name for field resolution
        orderedAliases.add(tableAlias);
        if (cteAliasTableNames == null)
            cteAliasTableNames = new HashMap<>();
        cteAliasTableNames.put(tableAlias, cteName); // CTE name for SQL generation
    }

    public void registerLateralSubquery(String alias, dev.webfx.stack.orm.expression.terms.Select<?> subquery, DbmsSqlSyntax dbmsSyntax, CompilerDomainModelReader modelReader) {
        if (lateralSqlMap == null)
            lateralSqlMap = new HashMap<>();
        if (subquery.getDomainClass() != null) {
            // Full select with FROM clause
            SqlCompiled compiled = dev.webfx.stack.orm.dql.sqlcompiler.ExpressionSqlCompiler.compileSelect(subquery, dbmsSyntax, false, false, modelReader);
            lateralSqlMap.put(alias, compiled.getSql());
        } else if (subquery.getFields() != null) {
            // Scalar select (no FROM) — compile just the field expressions using the parent's context.
            StringBuilder lateralSb = new StringBuilder("select ");
            Expression<?>[] fieldExprs = subquery.getFields().getExpressions();
            for (int i = 0; i < fieldExprs.length; i++) {
                if (i > 0) lateralSb.append(", ");
                Expression<?> field = fieldExprs[i];
                // Unwrap As to get the alias (since isTopLevelSelect() won't emit it)
                String fieldAlias = null;
                if (field instanceof As<?> asExpr) {
                    fieldAlias = asExpr.getAlias();
                    field = asExpr.getOperand();
                }
                // Compile the expression into an ephemeral clause
                SqlClause ephemeral = SqlClause.VALUES;
                StringBuilder origClause = sqlClauseBuilders.get(ephemeral);
                sqlClauseBuilders.put(ephemeral, new StringBuilder());
                dev.webfx.stack.orm.dql.sqlcompiler.ExpressionSqlCompiler.compileExpression(
                    field, new Options(this, ephemeral, ", ", false, false, false, modelReader)
                );
                lateralSb.append(sqlClauseBuilders.get(ephemeral));
                if (origClause != null)
                    sqlClauseBuilders.put(ephemeral, origClause);
                else
                    sqlClauseBuilders.remove(ephemeral);
                // Manually append the AS alias
                if (fieldAlias != null)
                    lateralSb.append(" as ").append(fieldAlias);
            }
            // "offset 0" blocks Postgres from pulling the subquery up into the parent: a
            // pulled-up lateral has its select expressions re-inlined at every reference
            // site, so an expensive scalar subquery referenced N times (e.g. in N aggregate
            // args) is evaluated N times per row instead of once.
            lateralSb.append(" offset 0");
            lateralSqlMap.put(alias, lateralSb.toString());
        }
        orderedAliases.add(alias);
    }

    /*
     * Union-level order by support. SQL restricts a set-operation order by to output columns
     * (names or ordinals), so union order keys are resolved against the first branch's select
     * columns using the two methods below. Both require this build's SQL to be FROZEN first
     * (toSql() already called): scratch-compiling a key may register new joins, and freezing
     * guarantees they cannot leak into the emitted SQL — an unmatched key (e.g. one that would
     * have needed a new join) is reported as an error by the caller instead.
     */

    /** Returns this build's select columns as individual SQL texts, in emission order (so ordinal = index + 1). */
    public List<String> getSelectColumns() {
        List<String> columns = new ArrayList<>();
        StringBuilder select = getClauseBuilder(SqlClause.SELECT);
        if (select == null)
            return columns;
        int depth = 0, start = 0;
        boolean inQuote = false;
        for (int i = 0; i < select.length(); i++) {
            char c = select.charAt(i);
            if (inQuote)
                inQuote = c != '\''; // '' escape re-enters quote state on the next quote char
            else if (c == '\'')
                inQuote = true;
            else if (c == '(' || c == '[')
                depth++;
            else if (c == ')' || c == ']')
                depth--;
            else if (c == ',' && depth == 0) {
                columns.add(select.substring(start, i).trim());
                start = i + 1;
            }
        }
        if (start < select.length())
            columns.add(select.substring(start).trim());
        return columns;
    }

    /** Compiles an expression into a scratch clause (leaving all real clauses untouched) and returns its SQL text. */
    public String compileToScratchSqlText(Expression<?> expression, CompilerDomainModelReader modelReader) {
        // HAVING (not VALUES): addColumnInClause strips the table alias in insert/values/update
        // clauses, which would make the text never match the select columns (which are qualified)
        SqlClause scratch = SqlClause.HAVING;
        StringBuilder origClause = sqlClauseBuilders.get(scratch);
        sqlClauseBuilders.put(scratch, new StringBuilder());
        try {
            dev.webfx.stack.orm.dql.sqlcompiler.ExpressionSqlCompiler.compileExpression(
                expression, new Options(this, scratch, ", ", false, false, false, modelReader));
            return sqlClauseBuilders.get(scratch).toString();
        } finally {
            if (origClause != null)
                sqlClauseBuilders.put(scratch, origClause);
            else
                sqlClauseBuilders.remove(scratch);
        }
    }

    public String addJoinCondition(String table1Alias, String column1Name, String table2Alias, String table2Name, String column2Name, boolean leftOuter) {
        SqlBuild logicalAliasBuild = getLogicalAliasBuild(table1Alias);
        if (logicalAliasBuild == null)
            logicalAliasBuild = this;
        return logicalAliasBuild.addJoinCondition2(table1Alias, column1Name, table2Alias, table2Name, column2Name, leftOuter);
    }

    private String addJoinCondition2(String table1Alias, String column1Name, String table2Alias, String table2Name, String column2Name, boolean leftOuter) {
        table1Alias = getSqlAlias(table1Alias, this);
        // LinkedHashMap: joins are emitted in the FROM clause in REGISTRATION order (select-clause
        // joins first, where-clause joins last). This matters for queries with more relations than
        // join_collapse_limit (8): only the first syntactic relations are freely reorderable by the
        // planner, so a hash-random order used to push semantically-driving joins (e.g. an
        // account-scoping person join referenced early in the select) out of the planner's reach.
        Map<Join, Join> table1Joins = joins.computeIfAbsent(table1Alias, k -> new LinkedHashMap<>());
        Join join = new Join(table1Alias, column1Name, table2Name, column2Name, null, leftOuter);
        Join existingJoin = table1Joins.get(join); // fetching the map to see if the join already exists (see Join.equals())
        if (existingJoin != null) {
            join = existingJoin;
            join.leftOuter &= leftOuter;
        } else {
            join.table2Alias = getNewTableAlias(table2Name, null, true);
            table1Joins.put(join, join);
        }
        if (table2Alias == null)
            recordLogicalAlias(join.table2Alias, join.table2Alias);
        else if (!table2Alias.equals(join.table2Alias)) {
            recordLogicalAlias(table2Alias, join.table2Alias);
            return table2Alias;
        }
        return join.table2Alias;
    }

    private static final class Join {
        // Join identifying fields (to include in equals and hash)
        final String table1Alias;
        final String column1Name;
        final String table2Name;
        final String column2Name;

        // Join attributes (not to include in equals and hash)
        String table2Alias;
        boolean leftOuter;

        private Join(String table1Alias, String column1Name, String table2Name, String column2Name, String table2Alias, boolean leftOuter) {
            this.table1Alias = table1Alias;
            this.column1Name = column1Name;
            this.table2Name = table2Name;
            this.column2Name = column2Name;
            this.table2Alias = table2Alias;
            this.leftOuter = leftOuter;
        }

        void appendTo(StringBuilder sb) {
            if (leftOuter)
                sb.append(" left");
            sb.append(" join ").append(table2Name).append(' ').append(table2Alias);
            if (column1Name.equals(column2Name)) // 'using' syntax when column names are identical
                sb.append(" using ").append(column1Name);
            else { // 'on' syntax
                sb.append(" on ").append(table2Alias).append('.').append(column2Name).append('=');
                if (table1Alias != null)
                    sb.append(table1Alias).append('.');
                sb.append(column1Name);
            }
        }

        static void appendJoins(Map<Join, Join> joinMap, StringBuilder sb) {
            if (joinMap != null)
                for (Join join : joinMap.keySet())
                    join.appendTo(sb);
        }

        static void appendNotYetAppendJoins(Map<Join, Join> joinMap, StringBuilder sb) {
            if (joinMap != null)
                for (Join join : joinMap.keySet()) {
                    StringBuilder sb2 = new StringBuilder();
                    join.appendTo(sb2);
                    String s2 = sb2.toString();
                    if (!sb.toString().contains(s2))
                        sb.append(s2);
                }
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Join join = (Join) o;

            if (!column1Name.equals(join.column1Name)) return false;
            if (!column2Name.equals(join.column2Name)) return false;
            if (!table1Alias.equals(join.table1Alias)) return false;
            return table2Name.equals(join.table2Name);
        }

        @Override
        public int hashCode() {
            int result = table1Alias == null ? 0 : table1Alias.hashCode();
            result = 31 * result + column1Name.hashCode();
            result = 31 * result + table2Name.hashCode();
            result = 31 * result + column2Name.hashCode();
            return result;
        }
    }


    // Some Strings static method helpers

    private static String _if(boolean condition, String s) {
        return condition && s != null ? s : "";
    }

    private static String _if(String before, StringBuilder s, String after, StringBuilder sb) {
        if (Strings.isNotEmpty(s)) {
            if (before != null)
                sb.append(before);
            sb.append(s);
            if (after != null)
                sb.append(after);
        }
        return "";
    }
}
